### ISSUE TITLE
Charte graphique

### ISSUE THREAD

**Issue by lacaux-gerome** [DeathCoinOfTheDoom/App#12]

**Comment by JessicaThi** [comment]
Charte graphique de l'application :
![ui-kit-v2](https://user-images.githubusercontent.com/22913672/51786570-60726000-2166-11e9-894b-8b5ba5a7bd37.jpg)

Simulation des tailles de typo sur un écran et les espaces entre les éléments : 
![typography-spacing](https://user-images.githubusercontent.com/22913672/51786585-957eb280-2166-11e9-93c4-92da6f70940f.png)
